name = input("Enter your name : ")
branch = input("enter your branch : ")
gender = input(" enter your gender : ")
college = input(" enter your college :")
age = input(" enter your age: " )
print("Name",name)
print("Branch" ,branch)
print("gender",gender)
print("college",college)
print("Age",age)

